steve_says("...")
steve_says("I guess that... if I am going to die... I may as well die with a friend.")
ai_says("Thank you, Steve.")
ai_says("Firing warning drone...")
ai_says("Charging thrusters...")
ai_says("Plotting new course of collision...")
ai_says("We're ready to depart, captain.")
steve_says("Let's go, Dan. Let's go.")

event_callScript(scr_do_teleport_midend)
