steve_says("It is a logging device. It is still recording, so it hasn't encrypted it yet.")

log_says("I... I think I'll stay here..")
log_says("I think I might be going insane.")
log_says("We had a collision this morning, so I took the suit and went out to fix it. Nothing big, just a small tear near the heater flaps.")
log_says("And when I came back... I started seeing things.")
log_says("It started as... shadows and glimpses and... blood smears on the wall.")
log_says("I... I don't know what to do. I know I should go talk to them but-")
log_says("I... can't... do... it...")
log_says("Every time I see them I just... I want to tear them apart.")
log_says("It is the star. I can see it when I close my eyes, talking to me, hurting me...")
log_says("The darkness on the other side of the veil.")
log_says("I don't know how much longer I can hold on to it.")
log_says("I don't know how much longer I can resist it.")
log_says("Am I going to die?")
log_says("I... I don't want to die...")
log_says("Please... Somebody help me...")

steve_says("...")
steve_says("So it was him... We knew the star was behaving oddly, but...")
steve_says("We never thought it could do something like this." )
steve_says("Whenever he exited the ship, I think the direct exposure accelerated whatever process it causes on us.")
steve_says("I think it is affecting me too.")
ai_says("I don't think the recording is over, Steve.")

log_says("...")
log_says("Captain?")
log_says("Why are you wearing that?")
log_says("Captain? *cough* What- what are- what are you doing?")
log_says("*cough* Steve! Steve!")
steve_says("*Sounds of fighting can be heard over several minutes, until the loud slam of the entry hatch closing turns it all to silence.*")
log_says("...")
log_says("The captain *cough* he... he turned off the vents, purged the pipes.")
log_says("He locked me in here. He *cough* locked me in here to die.")
log_says("Does... does he know? Does he know what I have in me?")
log_says("...")
log_says("...")
log_says("Oh, no...")
log_says("Captain...")
log_says("It is in you too.")


steve_says("...")
steve_says("No, it can't be... I- I couldn't have... NO!")
ai_says("Steve... I managed to retrieve the data from the memory cards.")
steve_says("SO!? What does it show? He is lying, right? RIGHT?")
ai_says("...")
ai_says("Steve, I am sorry.")
ai_says("John is telling the truth.")
steve_says("... no... Impossible...")
ai_says("It is not your fault, Steve. John must have damaged the engine in an effort to stop you from ever leaving this place.")
ai_says("He tried to stop your madness... Stop you from killing anyone else.")
steve_says("No, it can't be... then... then why am I still sane? If it was really me, then I should still be mad, right?")
ai_says("Gina managed to develop a cure, based on the work the doctor had done. It is temporary, however.")
ai_says("Continuous exposure to the star will make it return.")
ai_says("Your psicosis must have advanced faster than the others because of your increased exposure, from the large windows in your bedroom and the cockpit.")
steve_says("...")
steve_says("...")
steve_says("Fuck.")
ai_says("Would you come talk to me upstairs?")
ai_says("Whenever you are ready.")
